// default route

###
GET http://localhost:5000/

###
GET http://localhost:5000/api/users

###
POST http://localhost:5000/user
content-type: application/json

{
    "fullname": "Denis",
    "email": "denis@gmail.com"
}